CREATE TABLE test (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    body TEXT NOT NULL,
    created INTEGER NOT NULL
);

CREATE TABLE run (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    test_id INTEGER NOT NULL,
    created INTEGER NOT NULL,
    FOREIGN KEY (test_id) REFERENCES test (id)
)

